server:
  port: 8080

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true  
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:      
    initialization-mode: always    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true  h2:
    console:
      enabled: true
      path: /h2-console    
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG  
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG